/**
 * Report generation through the assistant.
 *
 * The single most important line in this file is that it **delegates to `@college-erp/reporting`
 * rather than implementing report queries here.** An assistant that could summarize reports from its
 * own query path would be a second reporting engine with its own — inevitably weaker — scope
 * enforcement, and the two would disagree about whose rows belong to whom. Calling `executeReport`
 * with an intersected grant list means a report generated by asking for it is byte-for-byte the
 * report the Reports screen would have produced.
 *
 * Authorization is the intersection of three grants, all required:
 *   `ai.view` × `reports.view` × the report's own `sourcePermission`
 * plus the tenant's `ai.assistant` entitlement (enforced by the controller's guards). Dropping any
 * one of them would let this endpoint become a strictly more powerful path to report data than the
 * Reports screen is, which is the exact shape of privilege-escalation bug.
 */

import { BadRequestException, ConflictException, ForbiddenException, Injectable } from '@nestjs/common';
import { AUDIT_ACTIONS, AUDIT_MODULES, PERMISSION_KEYS, type AuthenticatedUser } from '@college-erp/auth';
import type { Prisma } from '@college-erp/database';
import { executeReport, getReportDefinition, REPORT_TYPES, type ReportFilters, type ReportPrisma } from '@college-erp/reporting';
import type { AiGeneratedReportDto, AiTableColumnDto, AiTableRowDto } from '@college-erp/types';
import { TenantScopedPrismaService } from '../../common/prisma/tenant-scoped-prisma.service';
import { AuditService } from '../audit/audit.service';
import { PermissionsService } from '../rbac/permissions.service';
import {
  asReportScopeGrants,
  assertNonEmptyEffectiveScope,
  intersectReportScope,
  scopeContainsRequestedNode,
  scopeIsGlobal,
} from '../reports/reports-scope';

@Injectable()
export class AiReportService {
  constructor(
    private readonly tenantPrisma: TenantScopedPrismaService,
    private readonly permissions: PermissionsService,
    private readonly audit: AuditService,
  ) {}

  /**
   * Generates a report under the caller's intersected scope.
   *
   * `limit` is the assistant's own ceiling (AI_MAX_ROWS by default), applied on top of the engine's
   * preview limit. The engine still computes `totalCount` with its own uncapped count query, so a
   * capped answer states how many rows actually matched instead of implying the visible ones are
   * all of them.
   */
  async generate(
    user: AuthenticatedUser,
    input: {
      reportType: string;
      filters: ReportFilters;
      title?: string;
      limit: number;
      save: boolean;
    },
  ): Promise<AiGeneratedReportDto> {
    const definition = getReportDefinition(input.reportType);
    if (!definition) {
      throw new BadRequestException(
        `Unknown report type: ${input.reportType}. Available: ${availableReportTypes().join(', ')}.`,
      );
    }

    const grants = await this.resolveGrants(user, definition.sourcePermission);

    // An explicit campus/department/program in the request is a *narrowing*, and narrowing to a node
    // the caller cannot see is a request for someone else's rows. Refused rather than ignored: silently
    // ignoring it would return a wider answer than the one asked for, which is the opposite of safe.
    const requested = {
      ...(input.filters.campusId ? { campusId: input.filters.campusId } : {}),
      ...(input.filters.departmentId ? { departmentId: input.filters.departmentId } : {}),
      ...(input.filters.programId ? { programId: input.filters.programId } : {}),
    };
    if (Object.keys(requested).length > 0) {
      const contained = await scopeContainsRequestedNode(this.tenantPrisma, grants.effective, requested);
      if (!contained) {
        throw new ForbiddenException('The requested campus/department/program is outside your data scope.');
      }
    }

    const result = await executeReport(this.enginePrisma(), definition.reportType, input.filters, grants.effective, {
      mode: 'preview',
      limit: input.limit,
      actorUserId: user.id,
    });

    let savedReportId: string | null = null;
    if (input.save) {
      savedReportId = await this.saveReport(user, definition.reportType, input.title ?? definition.name, input.filters);
    }

    await this.audit.record({
      scope: 'TENANT',
      tenantId: user.tenantId,
      actorType: 'USER',
      actorUserId: user.id,
      action: AUDIT_ACTIONS.AI_REPORT_GENERATED,
      module: AUDIT_MODULES.AI,
      entityType: 'AiGeneratedReport',
      entityId: savedReportId ?? undefined,
      after: {
        reportType: definition.reportType,
        rowCount: result.rowCount,
        totalCount: result.totalCount,
        truncated: result.truncated,
        savedReportId,
        filters: result.filters,
        sourcePermission: definition.sourcePermission,
        isGlobal: grants.isGlobal,
      },
    });

    return {
      reportType: definition.reportType,
      title: input.title ?? definition.name,
      description: definition.description,
      columns: result.columns as AiTableColumnDto[],
      rows: result.rows as AiTableRowDto[],
      summary: result.summary,
      rowCount: result.rowCount,
      totalCount: result.totalCount,
      truncated: result.truncated,
      generatedAt: result.generatedAt,
      savedReportId,
    };
  }

  /**
   * Audits an export of an AI-generated report.
   *
   * Separate from generation because the compliance question that matters is not "what did it show"
   * but "what left the building" — so this records the format, the row count and the destination, and
   * is written by the controller's export route regardless of whether the report was regenerated or
   * downloaded from a previously saved one.
   */
  async recordExported(
    user: AuthenticatedUser,
    after: { reportType: string; format: string; rowCount: number; savedReportId?: string | null },
  ): Promise<void> {
    await this.audit.record({
      scope: 'TENANT',
      tenantId: user.tenantId,
      actorType: 'USER',
      actorUserId: user.id,
      action: AUDIT_ACTIONS.AI_REPORT_EXPORTED,
      module: AUDIT_MODULES.AI,
      entityType: 'SavedReport',
      entityId: after.savedReportId ?? undefined,
      after,
    });
  }

  /**
   * The report types this caller can actually generate, for the UI's picker.
   *
   * Filtered to the same intersection `generate()` enforces, so the picker can never offer a report
   * the endpoint would then refuse — a UI that offers an action it will reject is worse than one that
   * shows nothing.
   */
  async catalog(user: AuthenticatedUser) {
    const effective = await this.permissions.getEffectivePermissionsWithScope(user.tenantId, user.id);
    const aiGrants = asReportScopeGrants(effective[PERMISSION_KEYS.AI_VIEW] ?? []);
    const reportGrants = asReportScopeGrants(effective[PERMISSION_KEYS.REPORTS_VIEW] ?? []);
    if (aiGrants.length === 0 || reportGrants.length === 0) return [];

    const out = [];
    for (const reportType of availableReportTypes()) {
      const definition = getReportDefinition(reportType);
      if (!definition) continue;
      const sourceGrants = asReportScopeGrants(effective[definition.sourcePermission] ?? []);
      if (sourceGrants.length === 0) continue;
      const merged = await intersectReportScope(this.tenantPrisma, aiGrants, sourceGrants);
      out.push({
        reportType: definition.reportType,
        name: definition.name,
        description: definition.description,
        category: definition.category,
        sourcePermission: definition.sourcePermission,
        supportedFilters: definition.supportedFilters,
        // Whether the intersection collapses to the whole institution, so the UI can warn that an
        // export may contain every row rather than only this user's slice.
        isGlobal: scopeIsGlobal(merged),
      });
    }
    return out;
  }

  // ── Internals ─────────────────────────────────────────────────────────────

  /**
   * `ai.view` × `reports.view` × the report's `sourcePermission`, intersected.
   *
   * `assertNonEmptyEffectiveScope` throws rather than degrading to "no results": a caller whose
   * grants do not overlap must be told their role does not cover this, not shown an empty report
   * that reads like the college has no data.
   */
  private async resolveGrants(user: AuthenticatedUser, sourcePermission: string) {
    const effective = await this.permissions.getEffectivePermissionsWithScope(user.tenantId, user.id);

    const aiGrants = asReportScopeGrants(effective[PERMISSION_KEYS.AI_VIEW] ?? []);
    const reportGrants = asReportScopeGrants(effective[PERMISSION_KEYS.REPORTS_VIEW] ?? []);
    const sourceGrants = asReportScopeGrants(effective[sourcePermission] ?? []);

    if (aiGrants.length === 0) throw new ForbiddenException('Missing required permission: ai.view');
    if (reportGrants.length === 0) throw new ForbiddenException('Missing required permission: reports.view');
    if (sourceGrants.length === 0) {
      throw new ForbiddenException(`Missing required permission: ${sourcePermission}`);
    }

    // Three-way intersection: reports.view is intersected first, then the report's own source
    // permission on top of the AI entry grant. Intersecting pairwise-into-one-list is what keeps the
    // result from being the union of any of them.
    const withReports = await intersectReportScope(this.tenantPrisma, reportGrants, sourceGrants);
    const effective2 = await intersectReportScope(this.tenantPrisma, aiGrants, withReports);
    assertNonEmptyEffectiveScope(effective2);

    return { effective: effective2, isGlobal: scopeIsGlobal(effective2) };
  }

  /**
   * Persists the run as a SavedReport.
   *
   * Writes the same `SavedReport` row the Reports screen writes — no `snapshot` column, because the
   * reporting engine re-derives scope from the caller's grants at execution time rather than trusting
   * a stored one. That is the right property to inherit here too: a saved AI report re-run next month
   * is scoped by next month's role assignments, not by a frozen copy of today's.
   *
   * The `(tenantId, ownerId, name)` unique means a repeated generate with the same title is a
   * conflict, not a duplicate row; reported as a 409 rather than an opaque 500.
   */
  private async saveReport(
    user: AuthenticatedUser,
    reportType: string,
    name: string,
    filters: ReportFilters,
  ): Promise<string> {
    try {
      const created = await this.untypedCreate().savedReport.create({
        data: {
          ownerId: user.id,
          name,
          reportType,
          filters: JSON.parse(JSON.stringify(filters)) as Prisma.InputJsonValue,
          createdBy: user.id,
          updatedBy: user.id,
        },
      });
      return created.id;
    } catch {
      throw new ConflictException('A saved report with that name already exists.');
    }
  }

  /**
   * The tenant-scope extension injects tenantId at runtime, so the generated create-input still
   * demands it at compile time. One cast, confined here — the same reason ReportsService has one.
   */
  private untypedCreate(): UntypedCreateClient {
    return this.tenantPrisma.client as unknown as UntypedCreateClient;
  }

  private enginePrisma(): ReportPrisma {
    return this.tenantPrisma.client as unknown as ReportPrisma;
  }
}

interface UntypedCreateDelegate {
  create(args: { data: Record<string, unknown> }): Promise<{ id: string }>;
}

interface UntypedCreateClient {
  savedReport: UntypedCreateDelegate;
}

/** The reporting engine's own type list, so this module cannot drift from the engine's catalog. */
function availableReportTypes(): string[] {
  return [...REPORT_TYPES];
}