/**
 * Single source of truth for the student 360 sub-resources' RBAC keys, audit-action constants,
 * Prisma model names, and relation includes. Keeps the services/controllers DRY and — like the
 * organization module's ENTITY_META — self-documenting.
 */

import {
  PERMISSION_KEYS as K,
  AUDIT_ACTIONS as A,
  type PermissionKey,
  type AuditAction,
} from '@college-erp/auth';

// ── Resource identifiers ────────────────────────────────────────────────────

export const STUDENT_RESOURCES = [
  'guardian',
  'document',
  'admission',
  'academicRecord',
  'enrollment',
  'attendance',
  'fee',
  'payment',
  'exam',
  'result',
  'certificate',
  'libraryLoan',
  'hostelBooking',
  'transportPass',
  'hold',
  'communication',
] as const;

export type StudentResource = (typeof STUDENT_RESOURCES)[number];

export interface StudentResourceMeta {
  /** Prisma model name (lowercase delegate on the TenantScopedPrismaClient). */
  model: string;
  /** PascalCase entity name for audit entityType / error messages. */
  entityType: string;
  viewKey: PermissionKey;
  createKey: PermissionKey;
  updateKey: PermissionKey;
  deleteKey: PermissionKey;
  createAuditAction: AuditAction;
  updateAuditAction: AuditAction;
  deleteAuditAction: AuditAction;
  /** Related records to include in list/get for the resource's DTO shape. */
  include?: Record<string, unknown>;
  /** Which fields are NOT direct columns (needed to keep Prisma happy on create/update). */
  relationFields?: readonly string[];
}

export const STUDENT_RESOURCE_META: Record<StudentResource, StudentResourceMeta> = {
  guardian: {
    model: 'guardian',
    entityType: 'Guardian',
    viewKey: K.STUDENTS_VIEW,
    createKey: K.STUDENTS_CREATE,
    updateKey: K.STUDENTS_UPDATE,
    deleteKey: K.STUDENTS_MANAGE,
    createAuditAction: A.STUDENT_GUARDIAN_CREATED,
    updateAuditAction: A.STUDENT_GUARDIAN_UPDATED,
    deleteAuditAction: A.STUDENT_GUARDIAN_DELETED,
  },
  document: {
    model: 'studentDocument',
    entityType: 'StudentDocument',
    viewKey: K.STUDENTS_VIEW,
    createKey: K.STUDENTS_CREATE,
    updateKey: K.STUDENTS_UPDATE,
    deleteKey: K.STUDENTS_MANAGE,
    createAuditAction: A.STUDENT_DOCUMENT_UPLOADED,
    updateAuditAction: A.STUDENT_DOCUMENT_UPDATED,
    deleteAuditAction: A.STUDENT_DOCUMENT_DELETED,
  },
  admission: {
    model: 'studentAdmission',
    entityType: 'StudentAdmission',
    viewKey: K.STUDENTS_VIEW,
    createKey: K.STUDENTS_CREATE,
    updateKey: K.STUDENTS_UPDATE,
    deleteKey: K.STUDENTS_MANAGE,
    createAuditAction: A.STUDENT_ADMISSION_RECORDED,
    updateAuditAction: A.STUDENT_ADMISSION_UPDATED,
    deleteAuditAction: A.STUDENT_ADMISSION_DELETED,
    include: { program: true, academicYear: true },
    relationFields: ['program', 'academicYear'],
  },
  academicRecord: {
    model: 'studentAcademicRecord',
    entityType: 'StudentAcademicRecord',
    viewKey: K.STUDENTS_VIEW,
    createKey: K.STUDENTS_CREATE,
    updateKey: K.STUDENTS_UPDATE,
    deleteKey: K.STUDENTS_MANAGE,
    createAuditAction: A.STUDENT_ACADEMIC_RECORD_CREATED,
    updateAuditAction: A.STUDENT_ACADEMIC_RECORD_UPDATED,
    deleteAuditAction: A.STUDENT_ACADEMIC_RECORD_DELETED,
  },
  enrollment: {
    model: 'studentEnrollment',
    entityType: 'StudentEnrollment',
    viewKey: K.STUDENTS_VIEW,
    createKey: K.STUDENTS_CREATE,
    updateKey: K.STUDENTS_UPDATE,
    deleteKey: K.STUDENTS_MANAGE,
    createAuditAction: A.STUDENT_ENROLLED,
    updateAuditAction: A.STUDENT_ENROLLMENT_UPDATED,
    deleteAuditAction: A.STUDENT_ENROLLMENT_UPDATED,
    include: { academicYear: true, term: true, program: true, section: true, batch: true },
    relationFields: ['academicYear', 'term', 'program', 'section', 'batch'],
  },
  attendance: {
    model: 'studentAttendance',
    entityType: 'StudentAttendance',
    viewKey: K.ATTENDANCE_VIEW,
    createKey: K.ATTENDANCE_CREATE,
    updateKey: K.ATTENDANCE_UPDATE,
    deleteKey: K.ATTENDANCE_MANAGE,
    createAuditAction: A.STUDENT_ATTENDANCE_RECORDED,
    updateAuditAction: A.STUDENT_ATTENDANCE_UPDATED,
    deleteAuditAction: A.STUDENT_ATTENDANCE_UPDATED,
    include: { term: true },
    relationFields: ['term'],
  },
  fee: {
    model: 'studentFee',
    entityType: 'StudentFee',
    viewKey: K.FEES_VIEW,
    createKey: K.FEES_CREATE,
    updateKey: K.FEES_UPDATE,
    deleteKey: K.FEES_MANAGE,
    createAuditAction: A.STUDENT_FEE_ISSUED,
    updateAuditAction: A.STUDENT_FEE_UPDATED,
    deleteAuditAction: A.STUDENT_FEE_UPDATED,
    include: { term: true, payments: { orderBy: { paymentDate: 'desc' } } },
    relationFields: ['term', 'payments'],
  },
  payment: {
    model: 'studentPayment',
    entityType: 'StudentPayment',
    viewKey: K.PAYMENTS_VIEW,
    createKey: K.PAYMENTS_CREATE,
    updateKey: K.PAYMENTS_MANAGE,
    deleteKey: K.PAYMENTS_MANAGE,
    createAuditAction: A.STUDENT_PAYMENT_RECORDED,
    updateAuditAction: A.STUDENT_PAYMENT_UPDATED,
    deleteAuditAction: A.STUDENT_PAYMENT_REFUNDED,
    include: { studentFee: true },
    relationFields: ['studentFee'],
  },
  exam: {
    model: 'studentExam',
    entityType: 'StudentExam',
    viewKey: K.EXAMS_VIEW,
    createKey: K.EXAMS_CREATE,
    updateKey: K.EXAMS_UPDATE,
    deleteKey: K.EXAMS_MANAGE,
    createAuditAction: A.STUDENT_EXAM_CREATED,
    updateAuditAction: A.STUDENT_EXAM_UPDATED,
    deleteAuditAction: A.STUDENT_EXAM_CANCELLED,
    include: { term: true, program: true, section: true },
    relationFields: ['term', 'program', 'section'],
  },
  result: {
    model: 'studentResult',
    entityType: 'StudentResult',
    viewKey: K.RESULTS_VIEW,
    createKey: K.RESULTS_MANAGE,
    updateKey: K.RESULTS_MANAGE,
    deleteKey: K.RESULTS_MANAGE,
    createAuditAction: A.STUDENT_RESULT_RECORDED,
    updateAuditAction: A.STUDENT_RESULT_UPDATED,
    deleteAuditAction: A.STUDENT_RESULT_DELETED,
    include: { exam: true },
    relationFields: ['exam'],
  },
  certificate: {
    model: 'studentCertificate',
    entityType: 'StudentCertificate',
    viewKey: K.CERTIFICATES_VIEW,
    createKey: K.CERTIFICATES_CREATE,
    updateKey: K.CERTIFICATES_APPROVE,
    deleteKey: K.CERTIFICATES_MANAGE,
    createAuditAction: A.STUDENT_CERTIFICATE_REQUESTED,
    updateAuditAction: A.STUDENT_CERTIFICATE_STATUS_CHANGED,
    deleteAuditAction: A.STUDENT_CERTIFICATE_STATUS_CHANGED,
  },
  libraryLoan: {
    model: 'studentLibraryLoan',
    entityType: 'StudentLibraryLoan',
    viewKey: K.LIBRARY_VIEW,
    createKey: K.LIBRARY_CREATE,
    updateKey: K.LIBRARY_UPDATE,
    deleteKey: K.LIBRARY_MANAGE,
    createAuditAction: A.STUDENT_LIBRARY_LOAN_ISSUED,
    updateAuditAction: A.STUDENT_LIBRARY_LOAN_UPDATED,
    deleteAuditAction: A.STUDENT_LIBRARY_LOAN_UPDATED,
  },
  hostelBooking: {
    model: 'studentHostelBooking',
    entityType: 'StudentHostelBooking',
    viewKey: K.HOSTEL_VIEW,
    createKey: K.HOSTEL_CREATE,
    updateKey: K.HOSTEL_UPDATE,
    deleteKey: K.HOSTEL_MANAGE,
    createAuditAction: A.STUDENT_HOSTEL_BOOKING_CREATED,
    updateAuditAction: A.STUDENT_HOSTEL_BOOKING_UPDATED,
    deleteAuditAction: A.STUDENT_HOSTEL_BOOKING_CANCELLED,
  },
  transportPass: {
    model: 'studentTransportPass',
    entityType: 'StudentTransportPass',
    viewKey: K.TRANSPORT_VIEW,
    createKey: K.TRANSPORT_CREATE,
    updateKey: K.TRANSPORT_UPDATE,
    deleteKey: K.TRANSPORT_MANAGE,
    createAuditAction: A.STUDENT_TRANSPORT_PASS_CREATED,
    updateAuditAction: A.STUDENT_TRANSPORT_PASS_UPDATED,
    deleteAuditAction: A.STUDENT_TRANSPORT_PASS_CANCELLED,
  },
  hold: {
    model: 'studentHold',
    entityType: 'StudentHold',
    viewKey: K.STUDENTS_VIEW,
    createKey: K.STUDENTS_MANAGE,
    updateKey: K.STUDENTS_MANAGE,
    deleteKey: K.STUDENTS_MANAGE,
    createAuditAction: A.STUDENT_HOLD_PLACED,
    updateAuditAction: A.STUDENT_HOLD_UPDATED,
    deleteAuditAction: A.STUDENT_HOLD_LIFTED,
  },
  communication: {
    model: 'studentCommunication',
    entityType: 'StudentCommunication',
    viewKey: K.STUDENTS_VIEW,
    createKey: K.STUDENTS_UPDATE,
    updateKey: K.STUDENTS_UPDATE,
    deleteKey: K.STUDENTS_MANAGE,
    createAuditAction: A.STUDENT_COMMUNICATION_LOGGED,
    updateAuditAction: A.STUDENT_COMMUNICATION_LOGGED,
    deleteAuditAction: A.STUDENT_COMMUNICATION_LOGGED,
  },
};

/** Event-type strings written to StudentActivity — free-form, documented here. */
export const STUDENT_EVENTS = {
  CREATED: 'student.created',
  UPDATED: 'student.updated',
  STATUS_CHANGED: 'student.status_changed',
  ARCHIVED: 'student.archived',
  RESTORED: 'student.restored',
  GUARDIAN_CREATED: 'guardian.created',
  GUARDIAN_UPDATED: 'guardian.updated',
  DOCUMENT_UPLOADED: 'document.uploaded',
  DOCUMENT_VERIFIED: 'document.verified',
  DOCUMENT_REJECTED: 'document.rejected',
  ADMISSION_RECORDED: 'admission.recorded',
  ACADEMIC_RECORD_CREATED: 'academic_record.created',
  ENROLLED: 'enrollment.enrolled',
  ENROLLMENT_WITHDRAWN: 'enrollment.withdrawn',
  ATTENDANCE_RECORDED: 'attendance.recorded',
  FEE_ISSUED: 'fee.issued',
  FEE_UPDATED: 'fee.updated',
  FEE_WAIVED: 'fee.waived',
  PAYMENT_RECORDED: 'payment.recorded',
  PAYMENT_REFUNDED: 'payment.refunded',
  EXAM_CREATED: 'exam.created',
  RESULT_RECORDED: 'result.recorded',
  RESULT_UPDATED: 'result.updated',
  CERTIFICATE_REQUESTED: 'certificate.requested',
  CERTIFICATE_STATUS_CHANGED: 'certificate.status_changed',
  LIBRARY_LOAN_ISSUED: 'library_loan.issued',
  LIBRARY_LOAN_RETURNED: 'library_loan.returned',
  HOSTEL_BOOKING_CREATED: 'hostel_booking.created',
  HOSTEL_CHECKED_IN: 'hostel_booking.checked_in',
  HOSTEL_CHECKED_OUT: 'hostel_booking.checked_out',
  TRANSPORT_PASS_CREATED: 'transport_pass.created',
  TRANSPORT_PASS_CANCELLED: 'transport_pass.cancelled',
  HOLD_PLACED: 'hold.placed',
  HOLD_LIFTED: 'hold.lifted',
  COMMUNICATION_LOGGED: 'communication.logged',
} as const;