import type { ReportColumn, ReportDefinition, ReportFilterKey, ReportType } from './types';

const FILTERS_ALL: ReportFilterKey[] = [
  'dateFrom',
  'dateTo',
  'campusId',
  'departmentId',
  'programId',
  'sectionId',
  'academicYearId',
  'termId',
  'search',
  'status',
];

export const REPORT_CATALOG: readonly ReportDefinition[] = [
  {
    reportType: 'ADMISSIONS',
    key: 'admissions.pipeline',
    name: 'Admissions pipeline',
    description: 'Applications by session, program, stage, merit score and campus.',
    category: 'Admissions',
    sourcePermission: 'admissions.view',
    supportedFilters: ['dateFrom', 'dateTo', 'campusId', 'departmentId', 'programId', 'academicYearId', 'search', 'status'],
    sourcePath: '/admissions',
    columns: [
      { key: 'applicationNumber', label: 'Application' },
      { key: 'fullName', label: 'Applicant' },
      { key: 'session', label: 'Session' },
      { key: 'program', label: 'Program' },
      { key: 'campus', label: 'Campus' },
      { key: 'status', label: 'Status' },
      { key: 'meritScore', label: 'Merit', format: 'number' },
      { key: 'meritRank', label: 'Rank', format: 'number' },
      { key: 'submittedAt', label: 'Submitted', format: 'datetime' },
    ],
  },
  {
    reportType: 'STUDENTS',
    key: 'students.registration',
    name: 'Student register',
    description: 'Enrolled students by campus, department, program, section and status.',
    category: 'Students',
    sourcePermission: 'students.view',
    supportedFilters: FILTERS_ALL,
    sourcePath: '/students',
    columns: [
      { key: 'admissionNumber', label: 'Admission #' },
      { key: 'rollNumber', label: 'Roll #' },
      { key: 'fullName', label: 'Student' },
      { key: 'status', label: 'Status' },
      { key: 'campus', label: 'Campus' },
      { key: 'program', label: 'Program' },
      { key: 'section', label: 'Section' },
      { key: 'admittedOn', label: 'Admitted', format: 'date' },
    ],
  },
  {
    reportType: 'ATTENDANCE',
    key: 'attendance.summary',
    name: 'Attendance register',
    description: 'Per-student attendance records by date, subject, term and status.',
    category: 'Academics',
    sourcePermission: 'attendance.view',
    supportedFilters: ['dateFrom', 'dateTo', 'campusId', 'departmentId', 'programId', 'sectionId', 'termId', 'search', 'status'],
    sourcePath: '/attendance',
    columns: [
      { key: 'date', label: 'Date', format: 'date' },
      { key: 'admissionNumber', label: 'Admission #' },
      { key: 'student', label: 'Student' },
      { key: 'subject', label: 'Subject' },
      { key: 'attendanceType', label: 'Type' },
      { key: 'status', label: 'Status' },
      { key: 'markMethod', label: 'Marked via' },
    ],
  },
  {
    reportType: 'FEES',
    key: 'fees.outstanding',
    name: 'Fee ledger',
    description: 'Fee lines with billed, paid, waived, balance and due-date ageing.',
    category: 'Finance',
    sourcePermission: 'fees.view',
    supportedFilters: ['dateFrom', 'dateTo', 'campusId', 'departmentId', 'programId', 'academicYearId', 'termId', 'search', 'status'],
    sourcePath: '/fees/reports',
    columns: [
      { key: 'student', label: 'Student' },
      { key: 'admissionNumber', label: 'Admission #' },
      { key: 'headName', label: 'Fee head' },
      { key: 'amountCents', label: 'Billed', format: 'currency' },
      { key: 'paidCents', label: 'Paid', format: 'currency' },
      { key: 'waivedCents', label: 'Waived', format: 'currency' },
      { key: 'balanceCents', label: 'Balance', format: 'currency' },
      { key: 'status', label: 'Status' },
      { key: 'dueDate', label: 'Due', format: 'date' },
    ],
  },
  {
    reportType: 'EXAMS',
    key: 'exams.sessions',
    name: 'Examination sessions',
    description: 'Exam cycles with subject and registration counts by program and term.',
    category: 'Examinations',
    sourcePermission: 'exams.view',
    supportedFilters: ['dateFrom', 'dateTo', 'departmentId', 'programId', 'academicYearId', 'termId', 'search', 'status'],
    sourcePath: '/exams',
    columns: [
      { key: 'code', label: 'Code' },
      { key: 'name', label: 'Examination' },
      { key: 'program', label: 'Program' },
      { key: 'term', label: 'Term' },
      { key: 'status', label: 'Status' },
      { key: 'subjectCount', label: 'Subjects', format: 'number' },
      { key: 'registrationCount', label: 'Registrations', format: 'number' },
      { key: 'startDate', label: 'Starts', format: 'date' },
    ],
  },
  {
    reportType: 'PLACEMENTS',
    key: 'placements.outcomes',
    name: 'Placement outcomes',
    description: 'Final placement state, package and recruiting company per student.',
    category: 'Placements',
    sourcePermission: 'placements.view',
    supportedFilters: ['dateFrom', 'dateTo', 'campusId', 'departmentId', 'programId', 'academicYearId', 'search', 'status'],
    sourcePath: '/placements',
    columns: [
      { key: 'student', label: 'Student' },
      { key: 'admissionNumber', label: 'Admission #' },
      { key: 'program', label: 'Program' },
      { key: 'company', label: 'Company' },
      { key: 'position', label: 'Position' },
      { key: 'outcomeStatus', label: 'Outcome' },
      { key: 'finalPackageCents', label: 'Package', format: 'currency' },
      { key: 'placedAt', label: 'Placed', format: 'date' },
    ],
  },
  {
    reportType: 'LIBRARY',
    key: 'library.loans',
    name: 'Library circulation',
    description: 'Issued, overdue and returned loans with fines and member details.',
    category: 'Library',
    sourcePermission: 'library.view',
    supportedFilters: ['dateFrom', 'dateTo', 'search', 'status'],
    sourcePath: '/library',
    columns: [
      { key: 'itemTitle', label: 'Title' },
      { key: 'itemAuthor', label: 'Author' },
      { key: 'itemCode', label: 'Item code' },
      { key: 'member', label: 'Member' },
      { key: 'status', label: 'Status' },
      { key: 'borrowedAt', label: 'Borrowed', format: 'date' },
      { key: 'dueDate', label: 'Due', format: 'date' },
      { key: 'returnedAt', label: 'Returned', format: 'date' },
      { key: 'fineCents', label: 'Fine', format: 'currency' },
    ],
  },
  {
    reportType: 'HOSTEL',
    key: 'hostel.occupancy',
    name: 'Hostel occupancy',
    description: 'Bookings, rooms, beds and monthly rent across hostels.',
    category: 'Hostel',
    sourcePermission: 'hostel.view',
    supportedFilters: ['dateFrom', 'dateTo', 'campusId', 'departmentId', 'programId', 'search', 'status'],
    sourcePath: '/hostel',
    columns: [
      { key: 'student', label: 'Student' },
      { key: 'admissionNumber', label: 'Admission #' },
      { key: 'hostelName', label: 'Hostel' },
      { key: 'roomNumber', label: 'Room' },
      { key: 'bedNumber', label: 'Bed' },
      { key: 'status', label: 'Status' },
      { key: 'monthlyRentCents', label: 'Monthly rent', format: 'currency' },
      { key: 'checkInDate', label: 'Check-in', format: 'date' },
      { key: 'checkOutDate', label: 'Check-out', format: 'date' },
    ],
  },
  {
    reportType: 'TRANSPORT',
    key: 'transport.passes',
    name: 'Transport passes',
    description: 'Route/vehicle allocations, pass status, period and amount.',
    category: 'Transport',
    sourcePermission: 'transport.view',
    supportedFilters: ['dateFrom', 'dateTo', 'campusId', 'departmentId', 'programId', 'search', 'status'],
    sourcePath: '/transport',
    columns: [
      { key: 'student', label: 'Student' },
      { key: 'admissionNumber', label: 'Admission #' },
      { key: 'routeName', label: 'Route' },
      { key: 'pickupPoint', label: 'Pickup' },
      { key: 'vehicleNumber', label: 'Vehicle' },
      { key: 'status', label: 'Status' },
      { key: 'amountCents', label: 'Amount', format: 'currency' },
      { key: 'periodStart', label: 'From', format: 'date' },
      { key: 'periodEnd', label: 'To', format: 'date' },
    ],
  },
  {
    reportType: 'INVENTORY',
    key: 'inventory.stock',
    name: 'Inventory stock',
    description: 'Current stock balance per product and location with reorder level.',
    category: 'Inventory',
    sourcePermission: 'inventory.view',
    supportedFilters: ['dateFrom', 'dateTo', 'campusId', 'search', 'status'],
    sourcePath: '/inventory',
    columns: [
      { key: 'productCode', label: 'Code' },
      { key: 'product', label: 'Product' },
      { key: 'category', label: 'Category' },
      { key: 'location', label: 'Location' },
      { key: 'quantityOnHand', label: 'On hand', format: 'number' },
      { key: 'reservedQuantity', label: 'Reserved', format: 'number' },
      { key: 'reorderLevel', label: 'Reorder at', format: 'number' },
      { key: 'unitPriceCents', label: 'Unit price', format: 'currency' },
      { key: 'lastMovementAt', label: 'Last movement', format: 'datetime' },
    ],
  },
];

const BY_TYPE = new Map<ReportType, ReportDefinition>(REPORT_CATALOG.map((definition) => [definition.reportType, definition]));

export function getReportCatalog(): readonly ReportDefinition[] {
  return REPORT_CATALOG;
}

export function getReportDefinition(reportType: string): ReportDefinition | undefined {
  return BY_TYPE.get(reportType as ReportType);
}

export function isReportType(value: unknown): value is ReportType {
  return typeof value === 'string' && BY_TYPE.has(value as ReportType);
}

export function columnMap(definition: ReportDefinition): Map<string, ReportColumn> {
  return new Map(definition.columns.map((column) => [column.key, column]));
}
