/**
 * Query/DDL helpers on top of `psql` and the integrity probes a restore verification runs.
 *
 * Verification probes are caller-supplied SQL that must return a single number. The defaults check
 * that a restored archive contains a migrated schema (Prisma migration ledger complete) and the
 * platform's core tables — an archive that restores to an empty database fails verification.
 */
import { parseDatabaseUrl, pgToolEnv, resolvePgBinary, runCommand } from './pg-tools';

export interface IntegrityProbe {
  name: string;
  sql: string;
  /** Require exactly this value. */
  exact?: number;
  /** Require value >= min. */
  min?: number;
  /** Require value <= max. */
  max?: number;
}

export interface ProbeResult {
  name: string;
  value: number | null;
  expected?: string;
  ok: boolean;
  error?: string;
}

export interface RunSqlOptions {
  databaseUrl: string;
  sql: string;
  psqlPath?: string;
  timeoutMs?: number;
}

function expectedLabel(probe: IntegrityProbe): string | undefined {
  const parts: string[] = [];
  if (probe.exact !== undefined) parts.push(`= ${probe.exact}`);
  if (probe.min !== undefined) parts.push(`>= ${probe.min}`);
  if (probe.max !== undefined) parts.push(`<= ${probe.max}`);
  return parts.length > 0 ? parts.join(' and ') : undefined;
}

/** Runs one SQL statement, returning psql's tuples-only output. Throws on a non-zero exit. */
export async function runSql(options: RunSqlOptions): Promise<string> {
  const psql = resolvePgBinary('psql', options.psqlPath);
  if (!psql) {
    throw new Error('psql was not found. Install the PostgreSQL client tools or set BACKUP_PSQL_PATH.');
  }
  const connection = parseDatabaseUrl(options.databaseUrl);
  const result = await runCommand(
    psql,
    [
      '--no-align',
      '--tuples-only',
      '--quiet',
      '--set',
      'ON_ERROR_STOP=1',
      '--dbname',
      connection.sanitizedUrl,
      '--command',
      options.sql,
    ],
    { env: pgToolEnv(connection), timeoutMs: options.timeoutMs ?? 60_000 },
  );
  return result.stdout.trim();
}

/**
 * Runs a probe list sequentially, converting each into a pass/fail record instead of aborting the
 * whole verification on the first failure — operators want the full picture, not the first error.
 */
export async function runIntegrityProbes(options: {
  databaseUrl: string;
  probes: readonly IntegrityProbe[];
  psqlPath?: string;
  timeoutMs?: number;
}): Promise<ProbeResult[]> {
  const results: ProbeResult[] = [];
  for (const probe of options.probes) {
    const expected = expectedLabel(probe);
    try {
      const raw = await runSql({
        databaseUrl: options.databaseUrl,
        sql: probe.sql,
        ...(options.psqlPath ? { psqlPath: options.psqlPath } : {}),
        ...(options.timeoutMs ? { timeoutMs: options.timeoutMs } : {}),
      });
      const value = Number(raw);
      if (!Number.isFinite(value)) {
        results.push({ name: probe.name, value: null, ok: false, error: `Probe returned non-numeric output: ${raw.slice(0, 200)}`, ...(expected ? { expected } : {}) });
        continue;
      }
      const ok =
        (probe.exact === undefined || value === probe.exact) &&
        (probe.min === undefined || value >= probe.min) &&
        (probe.max === undefined || value <= probe.max);
      results.push({ name: probe.name, value, ok, ...(expected ? { expected } : {}) });
    } catch (error) {
      results.push({
        name: probe.name,
        value: null,
        ok: false,
        error: describeError(error),
        ...(expected ? { expected } : {}),
      });
    }
  }
  return results;
}

/**
 * Default restore-verification probes. Deliberately structural, not tenant-specific: they must hold
 * for every environment in every stage of the product's life.
 */
export function defaultPostgresProbes(): IntegrityProbe[] {
  return [
    {
      name: 'prisma_migrations_recorded',
      sql: 'SELECT count(*) FROM _prisma_migrations WHERE finished_at IS NOT NULL',
      min: 1,
    },
    {
      name: 'prisma_migrations_without_failures',
      sql: 'SELECT count(*) FROM _prisma_migrations WHERE finished_at IS NULL AND rolled_back_at IS NULL',
      max: 0,
    },
    { name: 'tenants_table_readable', sql: 'SELECT count(*) FROM tenants', min: 0 },
    { name: 'users_table_readable', sql: 'SELECT count(*) FROM users', min: 0 },
  ];
}

/** Database identifiers are generated by us, but quote and validate regardless. */
const IDENTIFIER_PATTERN = /^[a-z_][a-z0-9_]{0,62}$/;

export function assertDatabaseIdentifier(name: string): void {
  if (!IDENTIFIER_PATTERN.test(name)) {
    throw new Error(
      `Invalid database identifier "${name}": must match ${IDENTIFIER_PATTERN} (lower-case, <= 63 chars).`,
    );
  }
}

/** `<prefix><id>` sanitized into a valid, unique PostgreSQL identifier (<= 63 chars). */
export function buildScratchDatabaseName(prefix: string, uniquePart: string): string {
  const raw = `${prefix}${uniquePart}`
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, '_')
    .replace(/_+/g, '_')
    .replace(/^([^a-z_])/, '_$1');
  const name = raw.slice(0, 63).replace(/_+$/, '');
  assertDatabaseIdentifier(name);
  return name;
}

/** Swaps a URL's database for the maintenance database — used for CREATE/DROP DATABASE. */
export function toAdminDatabaseUrl(databaseUrl: string): string {
  const parsed = new URL(databaseUrl);
  parsed.pathname = '/postgres';
  return parsed.toString();
}

/** Drops (if needed, forcefully) and recreates a scratch database. */
export async function createScratchDatabase(options: {
  adminDatabaseUrl: string;
  name: string;
  psqlPath?: string;
}): Promise<void> {
  assertDatabaseIdentifier(options.name);
  await runSql({
    databaseUrl: options.adminDatabaseUrl,
    sql: `DROP DATABASE IF EXISTS "${options.name}" WITH (FORCE)`,
    ...(options.psqlPath ? { psqlPath: options.psqlPath } : {}),
  });
  await runSql({
    databaseUrl: options.adminDatabaseUrl,
    sql: `CREATE DATABASE "${options.name}"`,
    ...(options.psqlPath ? { psqlPath: options.psqlPath } : {}),
  });
}

export async function dropDatabase(options: {
  adminDatabaseUrl: string;
  name: string;
  psqlPath?: string;
}): Promise<void> {
  assertDatabaseIdentifier(options.name);
  await runSql({
    databaseUrl: options.adminDatabaseUrl,
    sql: `DROP DATABASE IF EXISTS "${options.name}" WITH (FORCE)`,
    ...(options.psqlPath ? { psqlPath: options.psqlPath } : {}),
  });
}

function describeError(error: unknown): string {
  if (error instanceof Error) {
    return error.message.slice(0, 4_000);
  }
  return String(error).slice(0, 4_000);
}
