import { isTenantScopedModel } from './client';

describe('tenant-guard model classification (from Prisma DMMF)', () => {
  const tenantScoped = [
    'Subscription',
    'SubscriptionItem',
    'TenantFeatureFlag',
    'UsageEvent',
    'User',
    'Role',
    'RolePermission',
    'UserRole',
    'Session',
    'Campus',
    'Department',
    'Program',
    'AcademicYear',
    'Term',
    'Room',
    'Building',
    'Batch',
    'Section',
    'Notification',
    'Document',
    'PasswordResetToken',
    'EmailVerificationToken',
    'MfaBackupCode',
    'TrustedDevice',
    'PasswordHistory',
    'TenantSecuritySettings',
    'TenantConfiguration',
    'WorkflowDefinition',
    'WorkflowState',
    'WorkflowTransition',
    'WorkflowTransitionApprover',
    'WorkflowInstance',
    'WorkflowApprovalTask',
    'Invoice',
    'InvoiceLineItem',
    'Entitlement',
    'Course',
    'CoursePrerequisite',
    'Curriculum',
    'CurriculumVersion',
    'CurriculumCourse',
    'CourseOffering',
    'CourseOfferingFaculty',
    'CourseRegistration',
    'AcademicAdvisingRecord',
    'AcademicProgressionRecord',
    'CourseBacklog',
    'AcademicCalendarEvent',
    'Timetable',
    'TimetablePeriod',
    'TimetableEntry',
    'TimetableHoliday',
    'FacultyAvailability',
    'TimetableConflict',
    'TimetableSubstitution',
    'TimetableHistory',
    'AttendanceSession',
    'AttendanceCorrectionRequest',
    'FacultyAttendance',
    'AttendanceDevice',
    'AttendanceDeviceUser',
    'AttendanceDeviceLog',
  ];

  const notTenantScoped = [
    'Tenant',
    'Plan',
    'FeatureFlag',
    'PlanFeatureFlag',
    'PlanModule',
    'Permission',
    'PlatformUser',
    'PlatformSession',
    'PlatformAuditLog',
    'LoginEvent',
    'PlatformMfaBackupCode',
    'SecurityEvent',
    'PlatformSecuritySettings',
    'SupportTicket',
    'SupportTicketComment',
  ];

  it.each(tenantScoped)('%s is tenant-scoped (guarded by the extension)', (model) => {
    expect(isTenantScopedModel(model)).toBe(true);
  });

  it.each(notTenantScoped)('%s is NOT tenant-scoped (accessed only via PlatformPrismaService)', (model) => {
    expect(isTenantScopedModel(model)).toBe(false);
  });
});
